# Rollback values for modelkit-demo
# This represents the working v3 version for rollback

modelkitRef:
  model: "jozu.ml/arnabchat2001/modelkit-demo:v3"  # GOOD model version (rollback target)
  code: "jozu.ml/arnabchat2001/modelkit-demo:v3"   # Same working code version

# Rollback settings (same as production but with working model)
replicaCount: 2

# Same resource limits as production
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 1000m
    memory: 2Gi

# Rollback environment
env:
  MODEL_PATH: "/model"
  ENVIRONMENT: "production"
  ROLLBACK_VERSION: "v3"
